pid /tmp/nginx.pid;
worker_processes auto;
events { worker_connections 256; }
http {
    access_log off;
    error_log /dev/stderr warn;
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path /tmp/proxy_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
    server {
        listen 5800;
        auth_basic "NAS JDownloader";
        auth_basic_user_file /etc/nginx/htpasswd;
        location / {
            proxy_pass http://jdownloader:5800;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Authorization "";
            proxy_read_timeout 3600s;
            proxy_buffering off;
        }
    }
}
